console.log("APP.JS");
import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
// import './layout';
// import './components';
import './tweet';
// import './home';
// import './profile';
// import './article';
import './services';
// import './auth';
// import './settings';
// import './editor';


// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  // 'app.layout',
  // 'app.components',
  'app.tweet',
  
  // 'app.home',
  // 'app.profile',
  // 'app.article',
  'app.services',
  // 'app.auth',
  // 'app.settings',
  // 'app.editor'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

console.log(window.app);
angular.module('app').config(appConfig);
console.log("pasa de config");
angular.module('app').run(appRun);
console.log("pasa de run");
angular.bootstrap(document, ['app'], {
  strictDi: true
});
